apiVersion: v1
kind: Secret
metadata:
  name: micropay-secrets
type: Opaque
stringData:
  POSTGRES_USER: micropay
  POSTGRES_PASSWORD: micropay_pass
  SPRING_DATASOURCE_USERNAME: micropay
  SPRING_DATASOURCE_PASSWORD: Manoj@8719895574
  JWT_SECRET: micropay_jwt_secret_key_123456
