apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
        - name: wallet-service
          image: nexus.example.com/micropay/wallet-service:latest
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: wallet-service-config
          env:
            # Config Server connection
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"
            
            # Database URL (matches ${WALLET_DB_URL} in config-repo/wallet-service.yml)
            - name: WALLET_DB_URL
              value: "jdbc:postgresql://postgres:5432/micropay_db"
            
            # Database credentials (matches ${POSTGRES_USER} and ${POSTGRES_PASSWORD} in config-repo)
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: micropay-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: micropay-secrets
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-service
spec:
  selector:
    app: wallet-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
