version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "kafka:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  config-server:
    build: ../../services/config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - kafka

  eureka-server:
    build: ../../services/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on:
      - config-server

  api-gateway:
    build: ../../services/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_URL}
    depends_on:
      - eureka-server
      - config-server

  auth-service:
    build: ../../services/auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - DB_URL=jdbc:postgresql://postgres:5432/micropay_auth_db
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_URL}
    depends_on:
      - kafka
      - postgres
      - eureka-server
      - config-server

  wallet-service:
    build: ../../services/wallet-service
    container_name: wallet-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - DB_URL=jdbc:postgresql://postgres:5432/micropay_wallet_db
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_URL}
    depends_on:
      - kafka
      - postgres
      - eureka-server
      - config-server

  payment-service:
    build: ../../services/payment-service
    container_name: payment-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - DB_URL=jdbc:postgresql://postgres:5432/micropay_payment_db
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_URL}
    depends_on:
      - kafka
      - postgres
      - eureka-server
      - config-server

  transaction-service:
    build: ../../services/transaction-service
    container_name: transaction-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - DB_URL=jdbc:postgresql://postgres:5432/micropay_transaction_db
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_URL}
    depends_on:
      - kafka
      - postgres
      - eureka-server
      - config-server

  notification-service:
    build: ../../services/notification-service
    container_name: notification-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - DB_URL=jdbc:postgresql://postgres:5432/micropay_notification_db
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_URL}
    depends_on:
      - kafka
      - postgres
      - eureka-server
      - config-server

  frontend:
    build: ../../frontend
    container_name: micropay-frontend
    ports:
      - "3000:3000"
    command: npm run preview -- --host 0.0.0.0 --port 3000
    depends_on:
      - api-gateway
