apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/micropay_db
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
